# Generated by Django 5.0.1 on 2024-02-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=50)),
                ('ci', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('anio_ingreso', models.PositiveIntegerField()),
                ('periodo_ingreso', models.CharField(max_length=50)),
                ('gestion', models.CharField(max_length=50)),
                ('periodo_salida', models.CharField(max_length=50)),
                ('nota', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('numero_acta', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_tesis', models.FileField(blank=True, null=True, upload_to='tesis/')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesis_modalidad', to='RepositorioTesisTitulados.modalidad')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesis_postulante', to='RepositorioTesisTitulados.estudiante')),
                ('tribunales', models.ManyToManyField(related_name='tesis_tribunales', to='RepositorioTesisTitulados.docente')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tesis_tutor', to='RepositorioTesisTitulados.docente')),
                ('tutor_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tesis_tutor_externo', to='RepositorioTesisTitulados.tutorexterno')),
            ],
        ),
    ]
